spring:
  application:
    name: ai-travel-planner
  jpa:
    open-in-view: false
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  flyway:
    locations: classpath:db/migration
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:}

vaadin:
  launch-browser: true
  frontend:
    hotdeploy: true
